resources:
  limits:
    cpus: 2.0
    memory: 4096

invidious:
  postgres_image_selector: postgres_17_image
  db_password: password
  hmac_secret: secret
  enable_companion: true
  companion_key: aaaa-bbbb-cccc-d
  admins:
    - admin@example.com
    - admin2@example.com
  registration_enabled: true
  login_enabled: true
  captcha_enabled: true
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080
  companion_port:
    bind_mode: published
    port_number: 8081

ix_volumes:
  config: /opt/tests/invidious/config
  postgres_data: /opt/tests/invidious/postgres_data

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
